baseURL: "https://robertschv.netlify.app"
#languageCode: "en-us"
copyright: Hans Robert Schneider
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    menu:
      main:
      - name: About
        url: /en/#About
        weight: 1
      - name: Experience
        url: /en/#experience
        weight: 2
      - name: Education
        url: /en/#education
        weight: 3
        #Projects
        #Achievements
      - name: Contact
        url: /en/#contact
        weight: 6
        #Dropdown menu
      - identifier: Languages
        title: Change the language
        name: Other languages
        weight: 7
      - identifier: Language1
        title: Klicken Sie hier, um zu Deutsch zu wechseln
        name: German
        url: /de
        parent: Languages
        weight: 1
      - identifier: Language2
        title: Haga clic aquí para cambiar a Español
        name: Spanish
        url: /es
        parent: Languages
        weight: 2
  de:
    languageName: Deutsch
    menu:
      main:
      - name: Über ich
        url: /de/#About
        weight: 1
      - name: Erleben Sie
        url: /de/#experience
        weight: 2
      - name: Bildung
        url: /de/#education
        weight: 3
        #Projects
        #Achievements
      - name: Kontakt
        url: /de/#contact
        weight: 6
        #Dropdown menu
      - identifier: Languages
        title: Sprache ändern
        name: Sprache ändern
        weight: 7
      - identifier: Language1
        title: Click here to switch to English
        name: Englisch
        url: /en
        parent: Languages
        weight: 1
      - identifier: Language2
        title: Haga clic aquí para cambiar a Español
        name: Spanisch
        url: /es
        parent: Languages
        weight: 2
    Title: Portfolio von Robert Schneider
    slug: projekte
    description: Alle (coolen) Dinge, der Robert Schneider gearbeitet hat, und auch (zukünftige) Projekte.
    twitter_handle: Robertschv_arbeit
  es:
    languageName: Español
    menu:
      main:
      - name: Acerca de mi
        url: /es/#About
        weight: 1
      - name: Experiencia
        url: /es/#experience
        weight: 2
      - name: Educación
        url: /es/#education
        weight: 3
        #Projects
        #Achievements
      - name: Contacto
        url: /es/#contact
        weight: 6
        #Dropdown menu
      - identifier: Languages
        title: Cambia de idioma
        name: Otros idiomas
        weight: 7
      - identifier: Language1
        title: Click here to switch to English
        name: Ingles
        url: /en
        parent: Languages
        weight: 1
      - identifier: Language2
        title: Klicken Sie hier, um zu Deutsch zu wechseln
        name: Alemán
        url: /de
        parent: Languages
        weight: 2
    Title: Portafolio de Robert Schneider
    slug: portfolio
    description: Todas las cosas (cooles) que Robert Schneider ha hecho de trabajo, y también (futuros) proyectos.
    twitter_handle: Robertschv_trabajo
    hero:
      enable: true
      intro: "Hola, mi nombre es"
      title: "Robert."
      subtitle: "I build things for the web"
      content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
      image: /images/hero.svg
      button:
        enable: true
        name: "Currículum"
        url: "https://rxresu.me/robertschv/principal-it-espaol"
      socialLinks:
        fontAwesomeIcons:
          - icon: fab fa-github
            url: https://github.com/Robertschv
          - icon: fab fa-linkedin
            url: https://www.linkedin.com/in/hans-robert-schneider-6794a9176/?locale=es_ES
          - icon: fab fa-twitter
            url: https://twitter.com/Robertschneider

title: "Robert Schneider- Portfolio"
theme: hugo-profile

Paginate: 3
#disqusShortname: gurusabarish
#googleAnalytics: G-DWJJVE27WD


markup:
  goldmark:
    renderer:
      unsafe: true



params:
  title: "Robert Schneider's Portfolio"
  description: All the things (cools) Hans Robert Schneider has done of work, and also (future) projects.
  twitter_handle: Robertschv_work
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.svg"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Robert."
    subtitle: "An IT man that loves to create software"
    content: "A passionate software developer. I build websites that looks great and I work on my skills everyday."
    image: /images/hero.jpg
    button:
      enable: true
      name: "Resume"
      url: "https://rxresu.me/robertschv/it-english"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Robertschv
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/hans-robert-schneider-6794a9176/
        - icon: fab fa-twitter
          url: https://twitter.com/Robertschneider

  # About
  about:
    enable: true
    title: "About me"
    image: "/images/IMG_0042-01.png"
    content: |-
      IT technical support, IT service management, software deployment and software developer, I also do equipment maintenance (Hardware and Software), I am currently a learning German, I am a Medium Technician in Computer Technician, with much enthusiasm to develop in this area.
    #I am currently working on a project that will be used to help people find the best way to get around the city.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "React"


  # Experience
  experience:
    enable: true
    items:
      - job: "Leading processor"
        company: "GE Credit Solutions"
        companyUrl: "http://ula.ve/"
        date: "Feb 2017 - Jul 2017"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Software Developer"
        company: "Amazon"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
          - Lead backend developer for a product.
          - Created a frontend design for a product.
      - job: "Junior Software Developer"
        company: "Apple"
        companyUrl: "https://example.com"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
          - Lead backend developer for a product.
          - Created a frontend design for a product.
      - job: "UI/UX Designer"
        company: "Netflix"
        companyUrl: "https://example.com"
        date: "June 2017 - Nov 2019"
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
          - Lead backend developer for a product.
          - Created a frontend design for a product.
      - job: "Intern at ULA school of engineering of systems"
        company: "Universidad de los Andes (VE)"
        companyUrl: "http://ula.ve/"
        date: "Feb 2017 - Jul 2017"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: robertschv@gmail.com
    btnName: Email me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com/Robertschv
      linkedin: https://www.linkedin.com/in/hans-robert-schneider-6794a9176/
      twitter: https://twitter.com/Robertschneider
