[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.96.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]

  # The base url of your site (optional, default = main URL set in Netlify)
  baseUrl = "https://robertschv.netlify.app"

  # Path to the sitemap URL (optional, default = /sitemap.xml)
  sitemapPath = "/sitemap.xml"

  # Time in seconds to not submit the sitemap after successful submission
  ignorePeriod = 0

  # Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
  providers = [
    "google",
    "yandex"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "accelerometer=(self), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), fullscreen=(self), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(self), usb=()"
    Content-Security-Policy = "policy"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
      max-age=0,
      no-cache,
      no-store,
      must-revalidate'''
